### ISSUE TITLE
[버그] 한번 로그인 후 앱을 다시 실행할 때 로그인할 수 없음 

### ISSUE THREAD

**Issue by hotheadfactory** [woowacourse-teams/2020-seller-lee-company#298]
### 버그 사항
직고래 앱에 로그인할 수 없습니다.

### 버그 simulation
직고래 앱을 설치 후 최초 실행 시에는 로그인이 정상적으로 가능하나, 멀티태스킹 창에서 앱을 닫고 다시 실행할 경우 앱의 초기 화면 상태에서 카카오톡 로그인 버튼을 눌러도 아무 일도 일어나지 않습니다. 설정에서 직고래 앱의 '데이터 삭제'를 하여야만 다시 로그인이 가능합니다. 

갤럭시 폴드 5G / 안드로이드 10 환경입니다. 추후 안드로이드 시뮬레이터 환경에서도 실행시켜 보고 오류가 발생하는지를 업데이트 하겠습니다.

### 원하던 상황
앱을 다시 실행하여도 로그인이 가능하거나, 로그인 정보를 기억하고 있어야 합니다.

**Comment by joseph415** [comment]
해당 부분 현재 해결하고 dev 에 올라와있어서 다음 릴리즈에 업데이트 할 예정입니다 :) 감사합니다.
