### ISSUE TITLE
[버그] 두 번째 로그인 시, 로그인 에러

### ISSUE THREAD

**Issue by SujinEmilyCho** [woowacourse-teams/2020-seller-lee-company#299]
### 버그 사항
첫 로그인 때는 로그인이 잘 되었는데요~
로그인이 풀린 이후 다시 로그인 버튼을 눌렀더니 에러 코드가 떠요! 

### 버그 simulation
안드로이드 스튜디오로 테스트 했구요~
디바이스는 Pixel 2 XL, OS는 Oreo(26) 사용했습니다.

첫 로그인은 잘 되었고 둘러보다가 채팅 메뉴로 들어갔어요.
디바이스 언어 설정이 영어로 되어 있어서 한글을 쓸 수가 없더라구요~
채팅에 참여하고 싶었는데 말이죠..😔
그래서 시스템 설정에서 한국어를 추가하고 돌아왔더니 직고래 앱 로그인이 풀려있었어요!
다시 로그인을 시도하니까 그 이후로 로그인이 안되고 에러가 나요..
 

### 원하던 상황
다시 로그인이 되면 좋겠어요
 

### **Screenshots**
![image](https://user-images.githubusercontent.com/49009406/93565748-d32cf080-f9c6-11ea-97de-eefaf95ca04f.png)

**Comment by joseph415** [comment]
해당 부분 현재 해결하고 dev 에 올라와있어서 다음 릴리즈에 업데이트 할 예정입니다 :) 감사합니다.
