### ISSUE TITLE
[버그] 채팅 - 자신이 작성하지 않은 메시지가 자신이 작성한 것으로 뜨는 이슈

### ISSUE THREAD

**Issue by SujinEmilyCho** [woowacourse-teams/2020-seller-lee-company#302]
### 버그 사항
채팅창에 들어가면 자신이 작성하지 않은 메시지가 작성한 기록으로 떠요!
 
### 버그 simulation
안드로이드 스튜디오로 Pixel 2 XL, Oreo(26) 사용했습니다.

채팅창에 들어가면 기존에 있던 채팅 내용이 뜨는데요. 제가 작성하지 않은 메시지가 제 기록으로 떠요!

### 원하던 상황
자신이 작성한 메시지만 자신의 기록으로 떠야하겠군요!
 

### **Screenshots**
![image](https://user-images.githubusercontent.com/49009406/93567915-5c91f200-f9ca-11ea-986c-9b33bdce6155.png)

**Comment by include42** [comment]
저 트와이스는 제가 쓴 건데, 제껄로 안떠서 버그 리포팅 하려고 했어욬ㅋㅋㅋㅋㅋㅋ
쪼밀리가 쓴 걸로 나오나보네요...

![Screenshot_2020-09-18-16-09-59-826_com sellerleecompany jikgorae](https://user-images.githubusercontent.com/6245801/93568940-d7a7d800-f9cb-11ea-97e8-5ce8bee335f2.png)

**Comment by SujinEmilyCho** [comment]
흐음!
카카오 로그인 했다가 중간에 튕긴 후 로그인이 한동안 안되었는데~
다시 로그인 하는 과정에서 회원 정보가 어딘가 꼬였을지도 모르겠네요ㅎㅎ

아 그리고 회원 가입 할 때 닉네임을 '쪼밀리'라고 했는데 카프카 채팅창으로 보니 제 닉네임이 뜨지 않네요!
마이페이지에선 제대로 뜹니다.
![image](https://user-images.githubusercontent.com/49009406/93569568-aed41280-f9cc-11ea-8783-a9db92052adc.png)

**Comment by kouz95** [comment]
제가 문제의 채팅을 개발하고 있는데..
지금 스토어에 올라간 버전은 google firebase 서버를 사용하고 있어요.
아무래도 서버를 직접 짤 수가 없으니 컨트롤이 안되서 문제가 많네요..
현재 개발중인 버전은 채팅 서버를 직접 짜놔서 채팅 관련 이슈들 많이 사라질 것으로 예상합니다.
릴리즈를 최대한 빠르게 해볼게요!

**Comment by hotheadfactory** [comment]
![Screenshot_20200918-185745](https://user-images.githubusercontent.com/13493184/93584948-08ded300-f9e1-11ea-9dbf-07af11487224.jpg)
'닉네임이 없는 채팅' 들이 모두 자기 것으로 표시되는 걸 보니, 본인 여부를 닉네임으로 판별하는 건가요?

**Comment by kouz95** [comment]
그랬었던것 같아요. 지금은 메세지마다 유저의 식별자를 넣어주도록 변경하였습니다.
