### ISSUE TITLE
[개선 사항] 채팅 길이 제한

### ISSUE THREAD

**Issue by include42** [woowacourse-teams/2020-seller-lee-company#307]
### 개선 사항
채팅에 긴 글을 넣으면 어떻게 되는지 테스트했는데, 
시 한편이 통으로 들어가네요. 화면이 꽉 찰 정도의 사이즈입니다.

지금 확인해보니 같은 분량의 게시글이 페이스북 메신저로도 가요.
아무래도 서비스 방향에 따라서는, 굳이 긴 글을 제한할 필요가 없겠지요
다만, 이 서비스의 방향에서 채팅이 메인이 아니라면, 길이 제한을 예를들어 300자로 둔다던가? 하는것도 좋다고 생각합니다.
<img width="316" alt="스크린샷 2020-09-18 오후 4 55 26" src="https://user-images.githubusercontent.com/6245801/93571907-0f188380-f9d0-11ea-9915-1e29456a0839.png">

### 기능 simulation
채팅 -> 채팅창에 긴 글 작성 -> 보내기

### 원하는 동작
일정 길이 이상 작성 시 텍스트가 입력되지 않음(채팅 창에서)

**Comment by lxxjn0** [comment]
150자 제한으로 처리해두었습니다 :)
