### ISSUE TITLE
[개선 사항] 게시글 작성

### ISSUE THREAD

**Issue by icyMojito** [woowacourse-teams/2020-seller-lee-company#309]
### 개선 사항
📌  Android 23(Mashmallow)에서 봤어요!
1. 게시글 작성 화면에서 제목을 입력하고 싶으면 '제목' <- 딱 요 두 글자 영역을 선택해야 입력이 가능합니다.
2. 상품 상세 설명 입력 창으로 넘어갔을 때 '내용을 입력해주세요'라는 문구를 선택해야 입력이 가능합니다.
3. 게시글에 카테고리 정보만 있어도 피드에 사진과 상세 글 내용 없이 등록이 됩니다.

### 기능 simulation
아래랑 같은 내용인 것 같아 생략합니다~

### 원하는 동작
1. 제목 영역 아무데나 선택해도 입력 커서가 떴으면 좋겠습니다. 가격 입력할 때처럼요!
2. 화면 아무 데나 선택해도 커서가 떴으면 좋겠어요!
3. 그냥 카테고리만 선택하고 완료를 눌렀는데 바로 피드에 넘어가서 호다닥 지웠어요!
    최소한 '제목'과 '가격'도 채워져 있어야 게시글을 등록할 수 있게끔 해주는 게 좋을 듯 하고,
    사진도 등록하지 않을 경우 디폴트로 보여줄 이미지가 있었으면 좋겠어요.
    사진이 없으니 하얗게만 나오는데 마치 어플에 오류 혹은 이미지가 로딩되지 않은 것처럼 느껴졌어요!

**Comment by lxxjn0** [comment]
이 부분에 대해 업데이트 완료했습니다 :)
