### ISSUE TITLE
[개선 사항] 프로필 디폴트 이미지

### ISSUE THREAD

**Issue by icyMojito** [woowacourse-teams/2020-seller-lee-company#310]
### 개선 사항
📌 Android 23(Mashmallow)에서 봤어요!
프로필에 등록한 사진이 없으면 피드의 게시글이나 프로필에서 하얀 화면으로 나옵니다.
사용에 불편함은 없지만 이 하얀 영역이 둥둥 떠보여서요! 어떤 것을 위한 자리인지 나타내면 더 좋을 듯 합니다.

### 기능 simulation
-

### 원하는 동작
프로필 디폴트 이미지가 있어서 따로 등록한 사진이 없어도 피드의 게시글이나 프로필에 사진 영역을 채워주었으면 해요!

**Comment by kouz95** [comment]
디폴트 이미지 추가했습니다! 감사합니다 😊
